// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDffMzHXvSPEw1kr-PU31NjEVSYopnbvds',
    appId: '1:842295971084:web:a4f38aa4365fb138c50d29',
    messagingSenderId: '842295971084',
    projectId: 'redmance-97802',
    authDomain: 'redmance-97802.firebaseapp.com',
    storageBucket: 'redmance-97802.appspot.com',
    measurementId: 'G-MYTGNTH3GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZajPm-EZ_fOuQu0_AIWKBKdZQa-933YM',
    appId: '1:842295971084:android:9c3d91ad9928b893c50d29',
    messagingSenderId: '842295971084',
    projectId: 'redmance-97802',
    storageBucket: 'redmance-97802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8_7ljMWD1EhBeWU_qkEpoZry3Fy_bCbQ',
    appId: '1:842295971084:ios:40173e23c6463a50c50d29',
    messagingSenderId: '842295971084',
    projectId: 'redmance-97802',
    storageBucket: 'redmance-97802.appspot.com',
    iosBundleId: 'com.example.redmance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8_7ljMWD1EhBeWU_qkEpoZry3Fy_bCbQ',
    appId: '1:842295971084:ios:40173e23c6463a50c50d29',
    messagingSenderId: '842295971084',
    projectId: 'redmance-97802',
    storageBucket: 'redmance-97802.appspot.com',
    iosBundleId: 'com.example.redmance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDffMzHXvSPEw1kr-PU31NjEVSYopnbvds',
    appId: '1:842295971084:web:e62597f4f6265706c50d29',
    messagingSenderId: '842295971084',
    projectId: 'redmance-97802',
    authDomain: 'redmance-97802.firebaseapp.com',
    storageBucket: 'redmance-97802.appspot.com',
    measurementId: 'G-PQ9QQ5W7GJ',
  );
}
